<?$codscuola = $_SESSION['codscuola'];
$pdf->SetFont('TitilliumWeb-SemiBold','',$titleSize);
$startY = 190;
$HRiga = 6;
$HRigaint =6;
$pdf->SetXY (20,$startY);
switch ($codscuola) {
    case 'AR':
        $pdf->Cell(0,$HRigaint,utf8_decode("ARCA Educazione"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->SetFont($fontdefault,'',12);
        $pdf->Cell(0,$HRigaint,utf8_decode("Cooperativa Sociale"), 0 ,1, 'L');
        $startY = $startY + 2*$HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Percorso educativo ADRIANO OLIVETTI"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Sede legale: Via T. Aspetti 248 - 35133 PADOVA"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Sede operativa: Via Pietro Giovanni Guarneri  - 35133  Padova"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Tel. 346 2245653"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("segreteria@arcascuola.it"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("www.arcascuola.it"), 0 ,1, 'L');
        $startY = $startY + 2*$HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Registro imprese Padova"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Codice Fiscale: 05484330286 - Partita iva: 05484330286"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("iscrizione albo nazionale società cooperative n° C138857"), 0 ,1, 'L');
        break;
    case 'PD':
        $pdf->Cell(0,$HRigaint,utf8_decode("Scuola Waldorf Padova"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->SetFont($fontdefault,'',12);
        $pdf->Cell(0,$HRigaint,utf8_decode("Steiner Waldorf Padova - Cooperativa Sociale"), 0 ,1, 'L');
        $startY = $startY + 2*$HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Scuola dell'Infanzia paritaria (c.m. 7 del 22/01/2002)"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Scuola Primaria paritaria (c.m. 2949 del 22/02/2017)"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Scuola Secondaria di I° grado iscritta all'albo delle Scuole non paritarie"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Sede legale e operativa: via Retrone, 20  - 35135  Padova"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Tel. 049 61.95.10  - Fax 049 88.94.39"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("segreteria@waldorfpadova.it"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("www.waldorfpadova.it"), 0 ,1, 'L');
        $startY = $startY + 2*$HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Registro imprese Padova"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Codice Fiscale: 92106210286 - Partita iva: 03577600285"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("c.c.i.a.a. n. 416913 iscrizione albo nazionale società cooperative n° A231181"), 0 ,1, 'L');
        break;
    case 'CI':
        $pdf->SetTextColor(148,53,53);
        $pdf->Cell(0,$HRigaint,utf8_decode("Scuola Steiner Waldorf Aurora"), 0 ,1, 'L');
        $pdf->SetTextColor($R,$G,$B);
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->SetFont($fontdefault,'',12);
        $pdf->Cell(0,$HRigaint,utf8_decode("Coop. Sociale Aurora"), 0 ,1, 'L');
        $startY = $startY + 2*$HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Scuola dell'Infanzia paritaria (PD1A080001)"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Scuola Primaria iscritta all'Albo Regionale delle Scuole Non Paritarie (PD1E026028)"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Scuola Secondaria di I° Grado iscritta all'Albo Regionale delle Scuole Non Paritarie (PD1MQZ500O)"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Sede legale e operativa: via Casaretta, 103  - 35013  Cittadella (PD)"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Tel. 049 94.013.03"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("info@aurorascuola.it "), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("www.aurorascuola.it"), 0 ,1, 'L');
        $startY = $startY + 2*$HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Registro imprese Padova"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Codice Fiscale e Partita iva: 03431790280"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("c.c.i.a.a. REA n. 310352 iscrizione albo nazionale società cooperative n° A122399"), 0 ,1, 'L');
        break;
    case "VR":
        $pdf->Cell(0,$HRigaint,utf8_decode("Scuola Steiner Waldorf Verona"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->SetFont($fontdefault,'',12);
        $pdf->Cell(0,$HRigaint,utf8_decode("Steiner Waldorf Verona - Cooperativa Sociale"), 0 ,1, 'L');
        $startY = $startY + 2*$HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Scuola dell'Infanzia non paritaria"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Scuola Primaria paritaria (1772 del 16/07/2019)"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Scuola Secondaria di I° Grado iscritta all'Albo Regionale delle Scuole Non Paritarie (VR1MV95009)"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,"", 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Sede legale e operativa : località Laura, 4 - frazione Grezzano - 37060  Mozzecane (VR)"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Tel. 045 5549256 - info@scuolawaldorfverona.it "), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("www.scuolawaldorfverona.it"), 0 ,1, 'L');
        $startY = $startY + 2*$HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Registro imprese Verona"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Codice Fiscale e Partita iva: 04028200238"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Numero REA VR 385885 - iscrizione albo nazionale società cooperative n° A212808"), 0 ,1, 'L');
        break;
    case "TN":
        $pdf->Cell(0,$HRigaint,utf8_decode("Scuola Steiner Waldorf Trento"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->SetFont($fontdefault,'',12);
        $pdf->Cell(0,$HRigaint,utf8_decode("Associazione Pedagogica Steineriana"), 0 ,1, 'L');
        $startY = $startY + 2*$HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Scuola Primaria Paritaria"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Scuola Secondaria di I° Grado Paritaria"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Scuola Superiore Paritaria"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,"", 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Sede legale e operativa : Via E. Conci 86 - Trento"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Tel.0461 930658 - segreteria@scuolasteiner-trento.it "), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("www.https://scuolasteiner-trento.it/.it"), 0 ,1, 'L');
        $startY = $startY + 2*$HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Registro imprese Trento"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Codice Fiscale: 96014820227 - Partita iva: 02183250220"), 0 ,1, 'L');
        $startY = $startY + $HRiga;
        $pdf->SetXY (20,$startY);
        $pdf->Cell(0,$HRigaint,utf8_decode("Numero REA TN - 159747"), 0 ,1, 'L');
        break;
    default:
        $pdf->Cell(170,8,utf8_decode("Codice scuola mancante per recupero intestazione"), 0,1, 'L');
        break;
}
?>